language: node_js
node_js:
  - "8"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache: yarn

jobs:
  include:
    - stage: check lint
      node_js: "8"
      script: echo "Performing yarn lint ..."
      script: yarn lint
    - stage: npm release
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "ofili@microsmart.tk"
        api_key: $NPM_API_KEY
        on:
          tags: true

